music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length = 50)
    album_title = models.CharField(max_length = 50)
    genre = models.CharField(max_length = 50)
    album_logo = models.CharField(max_length = 250)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)    
    file_type = models.CharField(max_length = 15)
    song_title = models.CharField(max_length = 50)
    is_favourite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

# Create your views here.
def index(request):
    all_albums = Album.objects.all()

    return render(request, 'music/index.html', {'all_albums':all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
 
    return render(request, 'music/detail.html', {'album':album})

def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):    
        return render(request, 'music/detail.html', {'album':album, 'error_message': "You did not select a valid song!"})    
    else:
        selected_song.is_favourite = True
        selected_song.save()   

    return render(request, 'music/detail.html', {'album':album})
     

music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h2>{{ album.album_title }}</h2>
<h3>{{ album.artist }}</h3>

{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}

<form action="{% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
    <input type="radio" id="song {{ forloop.counter }}" name="song" value="{{ song.id }}" />
    <label for="song {{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favourite %}
        <img src="http://i.imgur.com/b9b13Rd.png" alt="">
        {% endif %}
    </label><br>
    {% endfor %}
    <input type="submit" value="Favourite">
</form>

music/templates/music/index.html
{% load staticfiles %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<!-- <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet"> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- navbar -->
<nav class="navbar navbar-expand-sm bg-dark">
    <div class="container-fluid">
        
        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <!-- <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> -->
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Musiccc...</a>
        </div>
    </div>
</nav>

{% if all_albums %}

<h3>My Albums</h3>

<ul>
    {% for album in all_albums %}
    <li>
        <a href="{% url 'music:detail' album.id %}"> {{ album.album_title }} </a>
    </li>
    {% endfor %}
</ul>

{% else %}
<h3>No albums available yet</h3>

{% endif %}